### ISSUE TITLE
Nesting Element Selectors

### ISSUE THREAD

**Issue by Baldauf** [Rafflecopter/bemerald#6]
I would expect nested element selectors such as:
`.trigger-menu {
  @include E(btn) {
    @include E(glyph-wrap) {}}}`

to yield **`.trigger-menu__btn__glyph-wrap`**.

When bemerald is implemented, however, the same scss yields **`.trigger-menu__btn`** and **`.trigger-menu__glyph-wrap`** seperately.

**Comment by runningskull** [comment]
BEM [recommends against nested elements](http://getbem.com/faq/#css-nested-elements), so now bemerald will [fire an error](https://github.com/Rafflecopter/bemerald/blob/master/bemerald.scss#L174-L176) if it's detected.

A hotfix workaround is to use an explicit selector like `@include E(subelm) { &__subsubelm { ... } }`. The error message notes that as well.
